FROM bitnami/spark:3.1.2

USER root
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.0/hadoop-aws-3.2.0.jar --output /opt/bitnami/spark/jars/hadoop-aws-3.2.0.jar
RUN curl https://repo1.maven.org/maven2/io/openlineage/openlineage-spark/0.3.0/openlineage-spark-0.3.0.jar --output /opt/bitnami/spark/jars/openlineage-spark-0.3.0.jar

COPY ./dags/spark/ /opt/bitnami/spark
